package com.restaurantapp.utils

import android.content.Context
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import com.restaurantapp.data.entity.SalesData
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object PdfGenerator {

    fun generateSalesReport(context: Context, salesData: List<SalesData>): String {
        val dir = context.getExternalFilesDir("reports") ?: context.filesDir
        if (!dir.exists()) dir.mkdirs()
        val file = File(dir, "Sales_Report_${System.currentTimeMillis()}.pdf")

        val writer = PdfWriter(file)
        val pdfDocument = PdfDocument(writer)
        val document = Document(pdfDocument)


        val title = Paragraph("Restaurant Sales Report")
            .setBold()
            .setFontSize(18f)
            .setTextAlignment(TextAlignment.CENTER)
        document.add(title)
        document.add(Paragraph("Generated on: ${getCurrentDate()}").setFontSize(11f))
        document.add(Paragraph("\n"))


        val totalSales = salesData.sumOf { it.totalSales }
        val totalProfit = salesData.sumOf { it.totalProfit }

        val summaryTable = Table(UnitValue.createPercentArray(floatArrayOf(1f, 1f))).useAllAvailableWidth()
        summaryTable.addCell(
            Cell().add(Paragraph("Total Sales: ₹${String.format("%.2f", totalSales)}"))
                .setBackgroundColor(DeviceRgb(240, 250, 240))
        )
        summaryTable.addCell(
            Cell().add(Paragraph("Total Profit: ₹${String.format("%.2f", totalProfit)}"))
                .setBackgroundColor(DeviceRgb(240, 240, 255))
        )
        document.add(summaryTable)
        document.add(Paragraph("\n"))


        val table = Table(UnitValue.createPercentArray(floatArrayOf(3f, 2f, 2f))).useAllAvailableWidth()
        table.addHeaderCell(Cell().add(Paragraph("Date").setBold()))
        table.addHeaderCell(Cell().add(Paragraph("Total Sales").setBold()))
        table.addHeaderCell(Cell().add(Paragraph("Total Profit").setBold()))

        salesData.forEach { s ->
            table.addCell(Paragraph(s.date))
            table.addCell(Paragraph("₹${String.format("%.2f", s.totalSales)}"))
            table.addCell(Paragraph("₹${String.format("%.2f", s.totalProfit)}"))
        }
        document.add(table)

        document.add(Paragraph("\nReport generated by RestaurantApp").setFontSize(10f).setTextAlignment(TextAlignment.CENTER))
        document.close()

        return file.absolutePath
    }

    private fun getCurrentDate(): String {
        val sdf = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
        return sdf.format(Date())
    }
}
